version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/flask_test  # 배포할 경로로 수정
hooks:
  BeforeInstall:
    - location: codedeploy/install_dependencies.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: codedeploy/start_server.sh
      timeout: 300
      runas: ubuntu
