name: Deploy to AWS via CodeDeploy

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-2      # 예: 서울 리전
  S3_BUCKET: safebattery-s3       # 실제 S3 버킷 이름으로 변경
  APPLICATION_NAME: SafeBattery-CodeDeploy-AI
  DEPLOYMENT_GROUP: SafeBattery-CodeDeploy-AI-Group

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Prepare deployment artifact
        run: |
          mkdir -p deployment
          cp -r * deployment/
          cd deployment
          zip -r ../deployment-${{ github.sha }}.zip .

      - name: Upload artifact to S3
        run: |
          aws s3 cp deployment-${{ github.sha }}.zip s3://$S3_BUCKET/deployment-${{ github.sha }}.zip --region $AWS_REGION
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Create CodeDeploy deployment
        run: |
          aws deploy create-deployment \
            --application-name $APPLICATION_NAME \
            --deployment-group-name $DEPLOYMENT_GROUP \
            --s3-location bucket=$S3_BUCKET,key=deployment-${{ github.sha }}.zip,bundleType=zip \
            --region $AWS_REGION
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}